### ISSUE TITLE
[Question] Spec-Synthase usage example

### ISSUE THREAD

**Issue by allan-silva** [NatLibFi/Finto-suggestions#1]
Hi, I realized you are using Spec-Synthase, can I point the snippet bellow in usage examples in https://github.com/MicroarrayTecnologia/spec-synthase#usage-examples-with-zalandoconnexion-in-production ?

https://github.com/NatLibFi/Finto-suggestions/blob/774725217844d3fb2360d345d922f086a51e58e1/api/app.py#L89-L103

Thanks!

**Comment by pkronstrom** [comment]
@osma is this OK?

**Comment by osma** [comment]
Thanks @allan-silva for asking and @pkronstrom for the ping.

I don't see why this snippet couldn't be used as an example. This is open source code after all! So please do use it, but we'd appreciate a link back to this project.

**Comment by allan-silva** [comment]
Thanks @pkronstrom, @osma.
I already updated the production examples (https://github.com/MicroarrayTecnologia/spec-synthase#usage-examples-with-zalandoconnexion-in-production)
