### ISSUE TITLE
How to prevent empty suggestions from being imported

### ISSUE THREAD

**Issue by miguelahonen** [NatLibFi/Finto-suggestions#148]
Empty suggestions should be removed (suggestion without a title). How to prevent empty suggestion in the GitHub import?

**Comment by mirmaid** [comment]
Näyttää siltä, että tyhjissä ehdotuksissa ei ole tullut otsikko mukaan GitHubista, esim. https://github.com/Finto-ehdotus/YSE/issues/6320

**Comment by miguelahonen** [comment]
Saisitko @mirmaid selville antamasi esimerkin (Finto-ehdotus/YSE#6320) id:n. Näkyy urlissa kysymysmerkkien kohdalla: https://ehdotus.dev.finto.fi/suggestion/????

Tämä helpottaisi kyseisen vaillinaisen käsite-ehdotuksen löytämistä, koska tosiaan nimellä ei voi hakea, ei tietokannasta eikä hakutoiminnolla :-D

**Comment by ilona-x** [comment]
Tässä yksi vastaantullut tyhjä ehdotus: https://ehdotus.dev.finto.fi/suggestion/7212
ja sama vanhassa järjestelmässä: https://github.com/Finto-ehdotus/YSE/issues/7212

**Comment by ilona-x** [comment]
No nyt löytyi pitkä pätkä tyhjiä ehdotuksia löytyvät sivuilta 200-205, kun ehdotukset on järjestetty listaan "uusin ensin". Tässä vielä linkit ko. sivuille:
https://ehdotus.dev.finto.fi/suggestions/200
https://ehdotus.dev.finto.fi/suggestions/201
https://ehdotus.dev.finto.fi/suggestions/202
https://ehdotus.dev.finto.fi/suggestions/203
https://ehdotus.dev.finto.fi/suggestions/204
https://ehdotus.dev.finto.fi/suggestions/205

**Comment by miguelahonen** [comment]
> Tässä vastaantulleita tyhjiä ehdotuksia:
> 
> https://ehdotus.dev.finto.fi/suggestion/7212 & [Finto-ehdotus/YSE#7212](https://github.com/Finto-ehdotus/YSE/issues/7212)
> 
> https://ehdotus.dev.finto.fi/suggestion/7158 & [Finto-ehdotus/YSE#7158](https://github.com/Finto-ehdotus/YSE/issues/7158)
> 
> https://ehdotus.dev.finto.fi/suggestion/5626 & [Finto-ehdotus/YSE#5626](https://github.com/Finto-ehdotus/YSE/issues/5626)
> 
> https://ehdotus.dev.finto.fi/suggestion/5625 & [Finto-ehdotus/YSE#5625](https://github.com/Finto-ehdotus/YSE/issues/5625)
> 
> https://ehdotus.dev.finto.fi/suggestion/5519 & [Finto-ehdotus/YSE#5519](https://github.com/Finto-ehdotus/YSE/issues/5519)
> 
> https://ehdotus.dev.finto.fi/suggestion/5065 & [Finto-ehdotus/YSE#5065](https://github.com/Finto-ehdotus/YSE/issues/5065)
> 
> https://ehdotus.dev.finto.fi/suggestion/4816 & [Finto-ehdotus/YSE#4816](https://github.com/Finto-ehdotus/YSE/issues/4816)
> 
> https://ehdotus.dev.finto.fi/suggestion/4704 & [Finto-ehdotus/YSE#4704](https://github.com/Finto-ehdotus/YSE/issues/4704)

Aivan loistavaa!! :-D Kiitos! Thanks! Gracias!

**Comment by ilona-x** [comment]
Ja vielä lisäselvittelyä noista sivujen 200-205 tyhjinä näkyvistä ehdotuksista. Ne näyttävät olevan ensimmäisiä lomakkeella lähetettyjä ehdotuksia vanhaan ehdotusjärjestelmään kesä-elokuulta 2016.

Ensimmäiset ehdotuslomakkeella lähetetyt **uudet** termiehdotukset näkyvät uudessa järjestelmässä tyhjinä esimerkiksi:
aineistonhallinta https://github.com/Finto-ehdotus/YSE/issues/4441
antiage-ruokavalio https://github.com/Finto-ehdotus/YSE/issues/4442

ensimmäiset lomakkeella lähetetyt, jotka näkyvät uudessa järjestelmässä ei-tyhjinä:
runologia https://github.com/Finto-ehdotus/YSE/issues/4521
papaija https://github.com/Finto-ehdotus/YSE/issues/4522

Eli jos noista keksisi, mikä ehdotuksissa on erona, niin voisi päästä eteenpäin. 

Tuolloin samoihin aikoihin lähetetyt **muutos**-ehdotukset näyttäisivät siirtyneen uuteen järjestelmään ok.

**Comment by miguelahonen** [comment]
> Ja vielä lisäselvittelyä noista sivujen 200-205 tyhjinä näkyvistä ehdotuksista. Ne näyttävät olevan ensimmäisiä lomakkeella lähetettyjä ehdotuksia vanhaan ehdotusjärjestelmään kesä-elokuulta 2016.
> 
> Ensimmäiset ehdotuslomakkeella lähetetyt termiehdotukset näkyvät uudessa järjestelmässä tyhjinä esimerkiksi:
> aineistonhallinta [Finto-ehdotus/YSE#4441](https://github.com/Finto-ehdotus/YSE/issues/4441)
> antiage-ruokavalio [Finto-ehdotus/YSE#4442](https://github.com/Finto-ehdotus/YSE/issues/4442)
> 
> ensimmäiset lomakkeella lähetetyt, jotka näkyvät uudessa järjestelmässä ei-tyhjinä:
> runologia [Finto-ehdotus/YSE#4521](https://github.com/Finto-ehdotus/YSE/issues/4521)
> papaija [Finto-ehdotus/YSE#4522](https://github.com/Finto-ehdotus/YSE/issues/4522)
> 
> Eli jos noista keksisi, mikä ehdotuksissa on erona, niin voisi päästä eteenpäin.
> 
> Ja nyt vielä huomasin, että esim. tuo aineistonhallinta näkyy uudessa järjestelmässä **muutosehdotuksena** vaikka kyseessä siis uusi termi, jonka tyyppi pitäisi olla **käsite-ehdotus**.

Kiitos @ilona-x kovasti avusta debuggauksessa. Erinomaista tutkimustyötä! :-) Tämän ongelman kimppuun käyn aivan pian ja selvittelysi auttaa siinä huomattavasti. Tällä hetkellä Ehdotusjärjestelmän tietokannassa on 90 ehdotusta, jotka ovat tyhjiä tai lähes tyhjiä tai esimerkiksi puuttuu suomalainen preferred_label kokonaan. Tästä on hyvä aloittaa

**Comment by miguelahonen** [comment]
Maybe the quickest way to handle this problem is to do "needed moves" manually. Around 150 empty suggestions is fairly easy (and boring) to move to the new system. A reason, why it is so difficult to prevent empty suggestions from being imported is related to ways how a suggestion form (or ways to write a description fields for GitHub issues) has changed over time. It is almost impossible to parse a text area where you cannot find any regular string (in ~150 issues).. or to go through about 7,600 issues without scripting. But "empty" suggestions in the new Finto-suggestions are not empty issues in the GitHub so they can be read as long as the particular repo will be available.
