### ISSUE TITLE
Missing "date created" in the comments 

### ISSUE THREAD

**Issue by miguelahonen** [NatLibFi/Finto-suggestions#150]
New comments in the suggestion system and also imported GitHub comments need a property "dated created".

**Comment by mirmaid** [comment]
Kuluvan päivän kommenteissa tarvitaan myös tieto kellonajasta, jolloin kommentti on lisätty, jotta järjestäminen _viimeksi päivitetty ensin_ onnistuu (tämä on tärkeä ominaisuus kokousta edeltävinä päivinä).

**Comment by miguelahonen** [comment]
Conditions for showing the comment information changed and also vain text prints related to date times removed
