### ISSUE TITLE
Closed issues (suggestions) should have a tag "archived"

### ISSUE THREAD

**Issue by miguelahonen** [NatLibFi/Finto-suggestions#151]
Closed issues (suggestions) should have a tag "archived"

**Comment by miguelahonen** [comment]
Question with an example: 

In the YSE repository, the issue #7462 "Maailmankuva" is labeled by ACCEPTED. In the Suggestion system (straight imported from GitHub) the same suggestion is also labeled by ACCEPTED. The final goal is to begin to use a new platform - Suggestion system - instead of GitHub repositories. If we are not going to use the GitHub anymore, is there still a need to use the label ARCHIVED in the new Suggestion system? Is the label ACCEPTED enough?

**Comment by miguelahonen** [comment]
Now a short script runs sql updates for closed suggestions changing the status to ARCHIVED

**Comment by miguelahonen** [comment]
In the new suggestion system (in the user end) the suggestion (issue) #7379 "interstitiaaliset keuhkosairaudet" had originally after GitHub import four labels:
- käsite-ehdotus (suggestion_type.NEW)
- käsittelemätön (status.RECEIVED)
- alfo-kokous (suggestion_tags_association.ALLFO-KOKOUS)
- alustavasti-ok (suggestion_tags_association.ALUSTAVASTI OK)

After running the archiving script, the result is:
- käsite-ehdotus (suggestion_type.NEW)
- archived (was before "käsittelemätön" (status.RECEIVED)) <- **Is this a problem?**
- alfo-kokous (suggestion_tags_association.ALLFO-KOKOUS)
- alustavasti-ok (suggestion_tags_association.ALUSTAVASTI OK)

Should this issue be reopened?

**Comment by mirmaid** [comment]
^ Mitä tässä siis tapahtuu?
