### ISSUE TITLE
Tunniste-suodatusvalikon järjestys

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-suggestions#156]
Tyhjennä valinnat -kohta olisi hyvä olla ylinnä.

**Comment by miguelahonen** [comment]
A meeting listing in the Tag selector drop-down now includes Unselect all (Tyhjennä valinnat) options at the both ends of the list. It makes unselecting easier if the list is very long"

(Commited and pushed to the branch _Mika-Dev-reactions_and_labelcolors_ and will be pullable in the _Master branch_ later. Please, wait until the Pull Request for the Master.)
