### ISSUE TITLE
Kokous-suodatusvalikon järjestys

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-suggestions#157]
Valikossa olisi hyvä olla uusimmat ensin, koska niitä tarvitsee useimmin. YSO-kokoukset eivät nyt näy valikossa (johtuuko siitä että niiltä puuttuu päivämäärä).

**Comment by miguelahonen** [comment]
Draft meetings should be viewed on the list too

**Comment by miguelahonen** [comment]
The Drop-down list for meetings is now sorted by dates (the newest on top + meetings without the dates at the end of the list).

(Commited and pushed to the branch _Mika-Dev-reactions_and_labelcolors_ and will be pullable in the Master branch later. Please, wait until the Pull Request for the Master.)
