### ISSUE TITLE
Haun kohdistuminen ehdotuksen koko tekstiin

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-suggestions#159]
Millä logiikalla haku toimii?

- kun haen **balladit**, saan esim. tämän https://ehdotus.dev.finto.fi/suggestion/7497 - miksi?
- kun haen **Artossa**, saan esim. tämän https://ehdotus.dev.finto.fi/suggestion/4548 ?? Tässä https://ehdotus.dev.finto.fi/suggestion/5903 ei näy oikea teksti perustelut-kentässä, johon Artossa-haku osuu.

**Comment by miguelahonen** [comment]
https://ehdotus.dev.finto.fi/suggestion/5903 missing
!!!
Perustelut ehdotukselle
En varsianisesti minkään aineiston kuvailussa, kunhan yritän saada näitä KITO-termejä YSOon.
Perustelut ehdotukselle
En varsianisesti minkään aineiston kuvailussa, kunhan yritän saada näitä KITO-termejä YSOon.

**Comment by miguelahonen** [comment]
What is search based on?

**Comment by miguelahonen** [comment]
The rules for showing the fields related to reasons in a suggestion improved at SuggestionContent

**Comment by mirmaid** [comment]
^ Waat?

**Comment by mirmaid** [comment]
Onkos tätä nyt muutettu niin että haku kohdistuu vain otsikkoon?

**Comment by miguelahonen** [comment]
Haun pitäisi kohdistua oletuksena prefLabeleihin + id (kirjoitushetken tilanne), mutta voidaan valita (chechbox), että haetaan koko käsite-ehdotuksesta. Tässä issuessa ei nyt ei pohdita sitä, tuleeko kommentit mukaan vai ei
