### ISSUE TITLE
Järjestä-valikon käyttö ei palauta listan alkuun

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-suggestions#160]
Jos olen jollain käsitelistan sivulla (esim. viimeisellä) ja vaihdan järjestä-valikossa viitteiden järjestämisen tapaa (esim. valitsen vanhimmat ensin), jään sille sivulle jossa olen (olettaisin, että järjestyksen vaihtaminen palauttaa listan etusivulle. (Filttereiden pitää säilyä.))

**Comment by miguelahonen** [comment]
After sorting the listing should start from the beginning of entire list

**Comment by miguelahonen** [comment]
If sorting is used in the Suggestion listing and if user is not in the first page, the listing starts the listing from the first page"

### **To apply the changes in your browser, remember to use first Ctrl-F5 !!!**
