### ISSUE TITLE
Hyväksyttyjen ehdotusten kommenttikentät kokousnäkymässä

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-suggestions#163]
Hyväksytyissä ehdotuksissa näkyy tyhjä kommenttikenttä sekä ennen muita kommentteja (ja ennen jätä ehdotukseksi & hyväksy ehdotus -kuvakkeita), että muiden kommenttien jälkeen. Jos lisää kommentin ensimmäiseen kenttään, se siirtyy kuitenkin kommenttilistan loppuun. Tämä ylimääräinen kenttä ei näy, jos hyväksytyllä ehdotuksella ei ole kommentteja ennestään.

**Comment by miguelahonen** [comment]
Reminder for Mika: screenshot

**Comment by miguelahonen** [comment]
Related to suggestions accepted in the meetings.

**Comment by miguelahonen** [comment]
![Two_Editable_areas](https://user-images.githubusercontent.com/50104570/67688908-3b37aa00-f9a3-11e9-831d-4096f585127f.png)

**Comment by miguelahonen** [comment]
Poistetaan adminilta tilan muutokspainikkeiden yhteydessä olevan kommentikenttä ja siirretään painikkeet alas
