### ISSUE TITLE
Ehdotusten "vilkkuminen" kokousnäkymässä

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-suggestions#164]
Palatessa kokousnäkymässä tietystä ehdotuksesta takaisin kokouksen ehdotuslistaan, ehdotukset "vilistävät" hetken ennen kuin sivu näkyy normaalisti. Ihan kuin sivulla vilahtaisi jokin muu lista (kaikki käsitteet?) ja sitten tulosjoukko järjestyisi uudelleen. Joka tapauksessa melko häiritsevää, koska tämä tapahtuu joka kerta ehdotussivulta listaukseen palatessa (vaikka mitään suodatuksia tms. ei olisi käytössä).

**Comment by miguelahonen** [comment]
Usability of suggestion listing improved and some code lines cleaned up. However, there is a need to improve the sorting behavior later. Using a progress bar in the suggestion list loading prevents from annoying blinking.

**Comment by mirmaid** [comment]
Sivun latautuminen kestää nyt aivan liian kauan.

**Comment by miguelahonen** [comment]
You @kouralex found an exellent Vue-tool for Firefox Inspector 👍 and you said it helps a lot in repairing the Vue and state oriented bugs (you specifically mentioned this issue). Would you like to be assigned to this bug after the bugs #152 and #176 are closed? What do you think @MikkoAleksanteri?

**Comment by miguelahonen** [comment]
@mirmaid, oliko sivun latautuminen nyt siis jotenkin poikkeuksellisen hidasta eli yli 3,5 sekuntia? Vai yleensäkin on koko ajan ollut liian hidas?
