### ISSUE TITLE
Seuraava/edellinen käsite kokousnäkymässä

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-suggestions#165]
Kokouksessa pitäisi pystyä siirtymään ehdotuksesta seuraavaan tai edelliseen palaamatta listaussivulle. Tämä tuntuu kuitenkin nyt toimivan jollain sellaisella logiikalla, jota en onnistunut pitkällä yrittämiselläkään päättelemään. Ainakaan se ei siirrä listalla seuraavaan, numeroissa seuraavaan, tai seuraavaan samantyyppiseen ehdotukseen.

Tarkoitus olisi, että siirtyminen tapahtuu listalla seuraavaan/edelliseen ehdotukseen, huomioiden käytössä olevat suodattimet. Eli jos on valittu vain ehdotustyyppi muutosehdotus, siirrytään seuraavaan muutosehdotukseen, jos voimassa on lisäksi tunniste musiikki, niin seuraavaan niillä kriteereillä jne. Aina sivulla näkyvä listaus määrittää mikä on seuraava/edellinen.

**Comment by mirmaid** [comment]
Jätä ehdotukseksi / hyväksy ehdotus -kuvakkeet toimivat ilmeisesti samalla tavalla, eli siirtävät johonkin muuhun ehdotukseen suoraan, mutta tämä ei ole listalla seuraava ehdotus. En osaa sanoa onko tämä suora siirtyminen hyvä ratkaisu, mutta helpompi testata kunhan toimisi loogisesti.

**Comment by miguelahonen** [comment]
Logic behind the "next" action? How to get follow the sorting
