### ISSUE TITLE
Tunnisteen lisääminen

### ISSUE THREAD

**Issue by ilona-x** [NatLibFi/Finto-suggestions#176]
Kun lisää ehdotukselle tunnisteen ja avaa tämän jälkeen toisen ehdotuksen, näkyy aiemmin lisätty tunniste valittuna tunnistelistassa ja kun sen poisvalitsee, niin ehdotusjärjestelmä lisää ko. tunnisteen ehdotukselle.. 

Lisäksi joidenkin ehdotusten kohdalla tunnistelistassa näkyy valittuna satunnaisia tunnisteita. Kuitenkaan kaikkien ehdotusten kohdalla näitä ennaltavalittuja tunnisteita ei näy. 

![image](https://user-images.githubusercontent.com/21304210/67770501-2f112280-fa5f-11e9-917f-7add448150a3.png)

**Comment by mirmaid** [comment]
^ Korjattava ennen kuin voi mennä tuotantoon.

**Comment by ilona-x** [comment]
![image](https://user-images.githubusercontent.com/21304210/69952699-6bbdb700-1500-11ea-9d92-ecbf0c4e05b7.png)

En tiedä, liittyykö tähän samaan ongelmaan, mutta tilanne samantyyppinen. Eli nyt ehdotuksen (varfariini) yhteydessä näkyvät aiemmin avaamani ehdotuksen (teemat) kommentit. 

Ja lisäksi kun avaa ehdotuksen ja tämän jälkeen palaa takaisin ehdotuslistaan ja avaa toisen ehdotuksen, avautuu näkyviin aiemmin avattu ehdotus.
