### ISSUE TITLE
Kommenttien muokkaaminen/poisto

### ISSUE THREAD

**Issue by ilona-x** [NatLibFi/Finto-suggestions#177]
Peruskäyttäjän pitäisi voida muokata/poistaa vain omia kommenttejaan, mutta nyt myös peruskäyttäjällä näkyy kaikkien kommenttien kohdalla poista/muokkaa -toiminnot. Toisten kommentteja pääsee ikäänkuin muokkaaamaan ja muokkauksen tallentamaan, mutta nämä muokkaukset eivät kuitenkaan tallennu järjestelmään. Toisen käyttäjän kommentin kohdalla poisto-toiminto ei toimi.

Eli nuo toimimattomat poista/muokkaa-toiminnot olisi hyvä piilottaa näkyvistä.

**Comment by miguelahonen** [comment]
En saa omalla perustason käyttäjälläni toistettua ongelmaa. Sellainen ongelma kyllä asiassa ilmenee (ainakin minulla), että peruskäyttäjänä kirjoittamani kommentti näkyy vasta sivun uudelleenlatauksen jälkeen. Tosiaan, en itse pääse muokkaamaan peruskäyttäjänä muiden kommentteja ollenkaan. Hmm.. täytyypä miettiä miten ongelma saataisiin toistettua myös minun käyttäjälläni.

**Comment by ilona-x** [comment]
![image](https://user-images.githubusercontent.com/21304210/67835802-98db0c00-faf3-11e9-88d0-96fdb16a89f7.png)

**Comment by mirmaid** [comment]
Ilmenee myös mun peruskäyttäjällä

**Comment by ilona-x** [comment]
![image](https://user-images.githubusercontent.com/21304210/70990659-add52400-20ce-11ea-878f-592b26411c47.png)
Peruskäyttäjällä näkyvissä myös tunnisteiden muokkaus/poisto/lisäys -toiminnot, mutta nämäkään eivät toimi. Eli nämä pitäisi saada pois näkyvistä perustason käyttäjiltä.

**Comment by miguelahonen** [comment]
Now user can only edit his or her own comments or if he or she is admin user, editing of all comments is allowed.
