### ISSUE TITLE
Vulnerability problem

### ISSUE THREAD

**Issue by miguelahonen** [NatLibFi/Finto-suggestions#211]
4.12.19. faced vulnerability problem

**Comment by miguelahonen** [comment]
![Vul](https://user-images.githubusercontent.com/50104570/70216159-a1a0ac80-1747-11ea-9439-1796dcbff0ba.png)

**Comment by miguelahonen** [comment]
pyyaml is not in use

**Comment by miguelahonen** [comment]
DO:
[packages]
Jinja2 = ">=2.10.1"
or…
[dev-packages]
Jinja2 = ">=2.10.1"

**Comment by miguelahonen** [comment]
DELETE:
urllib3 is not in use

**Comment by miguelahonen** [comment]
DELETE:
werkzeug is not in use

**Comment by miguelahonen** [comment]
DELETE:
typed-ast is not in use

**Comment by osma** [comment]
werkzeug is used by Flask, which is used by Connexion. I don't think you can just delete it...

**Comment by miguelahonen** [comment]
Thanks Osma for your comment. That is true and it is not deleted. I noticed werkzeug as important. Finally, any of mentioned libs were not deleted

**Comment by miguelahonen** [comment]
Now:
pyyaml==5.2
jinja2==2.10.3
urllib3==1.25.7
werkzeug==0.16.0
