### ISSUE TITLE
Käyttäjälle asetetut ehdotukset -listaus ei toimi toivotulla tavalla

### ISSUE THREAD

**Issue by ilona-x** [NatLibFi/Finto-suggestions#226]
![image](https://user-images.githubusercontent.com/21304210/70991765-d4945a00-20d0-11ea-9dd1-c03914cf4d75.png)

Käyttäjälle asetetut ehdotukset -listalla näkyy ehdotuksia, joissa ei ole käsittelijää asetettu tai käsittelijäksi on asetettu joku toinen käyttäjä.

**Comment by ilona-x** [comment]
Näyttäisi siltä, että kun lisää ehdotukseen käsittelijän, tulee tuonne käyttäjän profiilisivun ehdotuslistaan kaikki ehdotukset, jotka olivat lisätyn ehdotuksen kanssa samalla sivulla. Tämä tilanne tapahtui testatessa admin-tunnuksella ja lisättäessä ehdotuksen käsittelijäksi tämä sama admin-käyttäjä.

**Comment by miguelahonen** [comment]
Toimii sittenkin. Fixes #226
