### ISSUE TITLE
No option to deselect meeting in search or in suggestion

### ISSUE THREAD

**Issue by kouralex** [NatLibFi/Finto-suggestions#243]
If one chooses a meeting for search, it cannot be deselected without clearing all filters like all the other filters.

**Comment by kouralex** [comment]
I just noticed that the same issue is in effect in suggestion page, too.

**Comment by kouralex** [comment]
Whilst this has been deemed closed, I highly suspect I have to reopen it. For example, look at the image below:

![image](https://user-images.githubusercontent.com/1723419/75419833-60cbc480-593f-11ea-8245-e87228224991.png)

I would prefer to have the option to deselect meeting in the dropdown list, as it is done for labels (see image below):

![image](https://user-images.githubusercontent.com/1723419/75420102-eb142880-593f-11ea-952e-c18c86ca7150.png)

Here you can just click on the selected filter to deselect it (additionally, it has the feature to deselect all labels, but that is not the case for meetings as only one meeting can be selected). However, I think the same feature could be incorporated here, too.

**Comment by miguelahonen** [comment]
Tehdään mieluummin uusi issue siihen liittyen, pitääkö kaikkien pudotusvalikkojen toiminnat yhdenmukaistaa versioon yksi mennessä vaiko ei. Nyt tehty korjaus tyhjentää tapaamisvalikon ja selkeästi tarjoaa mahdollisuuden poistaa valinnan, mikä issuessa alunperin kuvattu asia.

**Comment by miguelahonen** [comment]
Tämä issue on @kouralex, uusi issue kuvaamaasi asiaan

**Comment by miguelahonen** [comment]
Eli tämä #302
