### ISSUE TITLE
Sivutus (pagination) ei toimi

### ISSUE THREAD

**Issue by miguelahonen** [NatLibFi/Finto-suggestions#266]
Ongelman toisto:

1) Mene etusivulle

2) Järjestä -> "eniten kommentoitu"

3) Klikkaa ehdotuslistauksen alapuolella olevassa sivuvalinnassa viimeistä sivua (testatessa sivu 306)

4) Klikkaa sivuvalinnassa toiseksi viimeistä sivua (testatessa sivu 305)

5) Toista kohtaa (4) sivumäärää aina pienentäen (sivut ovat tyhjiä)

...mentäessä kohtien (4) ja (5) mukaisesti taaksepäin, sivut pysyvät aina tyhjinä, mutta mentäessä sivuvalinnasta suoraan sivulle yksi, listaus taas toimii ja sivuille voidaan siirtyä kaksi tai kolme pykälää eteenpäin, mutta ei silti viimeiselle sivulle.

[Joidenkin Järjestä-valikon valintojen ollessa alittuna, sivutus toimii siis alusta loppua kohti, mutta ei lopusta alkua kohti]

Ehdotus 1 tutkimisen kohteeksi: Vuex pitää yllä storen kautta statea, jossa voi olla tarpeen säilyttää sivutukseen liittyviä tietoja. Staten käytössä tai sen "tilassa" itsessään saattaa olla aiheeseen liittyvän ongelman lähde - ehkä.

Ehdotus 2 tutkimisen kohteeksi: pysyykö kaikilla sivuilla näytettävin ehdotusten kokonaismäärä samana kaikilla eri Järjestä-valikon valinnoilla, kun ei ole mitenkään suodatettu hakutulosta.

Nyt ehdotuksia on 7655 ja yhdellä sivulla näytetään 25 ehdotusta. Ehdotusten pitää siis jakautua 306 sivulle ja näyttää viimeisellä sivulla viisi ehdotusta - tämä toimii! 

[.. mutta mentäessä viimeiselle sivulle, sivu on tyhjä, kun on valittuna esimerkiksi "eniten kommentoitu"]

**Comment by kouralex** [comment]
Sanoisin, että tämä kannattaa korjata (=varmistaa toimivuus) issuen #300 yhteydessä.

**Comment by kouralex** [comment]
Näyttää alustavasti siltä, että kommenttien lajittelusta vastaavissa ohjelmakoodeissa https://github.com/NatLibFi/Finto-suggestions/blob/dcb7f9441eca3230bf3ce0e4c7a9906706454bc8/api/api/logic/utils.py#L72-L99 käytettävät filter()-määritykset eivät toimi oikein. Asia vaatii vielä lisäselvittelyä toimivan fiksin rakentamiseksi.
