### ISSUE TITLE
Peruskäyttäjällä näkyvissä ehdotuksen tapahtumien poisto-toiminto

### ISSUE THREAD

**Issue by ilona-x** [NatLibFi/Finto-suggestions#282]
Peruskäyttäjällä näkyy mahdollisuus poistaa ehdotuksen tapahtumia siis esim. tunnnisteen lisääminen, toiminto ei kuitenkaan toimi, eikä sen pidäkään toimia kuin admin-käyttäjillä
 
kyseessä siis vastaava ongelma kuin aiemmin toisten käyttäjien kommenttien poisto/muokkaus painikkeiden näkyminen peruskäyttäjällä https://github.com/NatLibFi/Finto-suggestions/issues/177

**Comment by kouralex** [comment]
Tämä on nyt korjattu.
