### ISSUE TITLE
Muokataan get_open_suggestion_skos-funktioon liityvä haku toimivammaksi

### ISSUE THREAD

**Issue by miguelahonen** [NatLibFi/Finto-suggestions#288]
(yse_term). Kuitenkin päädyttiin siihen, että suggestion/open/skos-endpointia pitää muutta seuraavasti:

in suggestions.py:

- muutetaan funktion nimi universaalimmaksi ja tarvittaessa refaktoroidaan
- yhdistetään et_open_suggestions_skos() ja get_suggestion_skos()
- tuloksena syntyy muokattu universaalimpi ja universaalimmaksi nimetty endpoint, jossa otetaan vastaan query-string-parametri, jonka kutsuja välittää urlin kautta.
- query-stringistä parsitaan tieto siitä,
-> mitkä ehdouksen staten ovat inklusiivisia tai eksklusiivisia 
-> onko mukana YSEssä
-> mikä on palautettavan paketin muoto (oletus: skos) 
-> mikä on palautettavan paketin formaatti (mandatory: turtle)

Alustava aikatauluarvio on 2-3 päivää

_Originally posted by @miguelahonen in https://github.com/NatLibFi/Finto-suggestions/pull/274#issuecomment-588121955_

**Comment by kouralex** [comment]
Vahingossa tein duplikaatti-issuen #300. Suljen tämän.
