### ISSUE TITLE
Uudelleenrefaktoroidaan haku

### ISSUE THREAD

**Issue by kouralex** [NatLibFi/Finto-suggestions#300]
Päädyttiin siihen, että suggestion/open/skos-endpointia pitää muuttaa seuraavasti:

in suggestions.py:

- muutetaan funktion nimi universaalimmaksi ja tarvittaessa refaktoroidaan
- yhdistetään et_open_suggestions_skos() ja get_suggestion_skos()
- tuloksena syntyy muokattu universaalimpi ja universaalimmaksi nimetty endpoint, jossa otetaan vastaan query-string-parametri, jonka kutsuja välittää urlin kautta.
- query-stringistä parsitaan tieto siitä,
-> mitkä ehdouksen staten ovat inklusiivisia tai eksklusiivisia 
-> onko mukana YSEssä
-> mikä on palautettavan paketin muoto (oletus: skos) 
-> mikä on palautettavan paketin formaatti (mandatory: turtle)

Alustava aikatauluarvio on 2-3 päivää

_Originally posted by @miguelahonen in https://github.com/NatLibFi/Finto-suggestions/pull/274#issuecomment-588121955_

**Comment by miguelahonen** [comment]
curl -X GET --header 'Accept: text/turtle' --header 'Authorization: Bearer ..YourSHAorSomethingForAuthorization.. ' 'http://localhost:8080/api/suggestions/skosfilter?filters=status:received.read.accepted.rejected.retained.archived|exclude:true/false|type:new/modify/both|yse:true/false/both|model:skos/dc/foaf|format:turtle/jsonld/xml/n3/ntriples|suggestion_id:0/suggestion_id:nnnn'

    1) At least one status flag should be used
    2) Status flags must be delimited by a dot (.)
    3) The 'pipe' is used as delimiter for query parameters 
    4) suggestion_id:0 returns all the filtered suggestions
    5) suggestion_id:nnnn retruns only one suggestion by suggestion id
    6) All the parameters must be defined in the query


Example:

curl -X GET --header 'Accept: text/turtle' --header 'Authorization: Bearer ABC123ABC123' 'http://localhost:8080/api/suggestions/skosfilter?filters=status:received.read.accepted.rejected.retained.archived|exclude:false|type:both|yse:both|model:skos|format:turtle|suggestion_id:0'

fixes #300
